---
# This file is centrally managed in https://github.com/<organization>/.github/
# Don't make changes to this file in this repo as they will be overwritten with changes made to the same file in
# the above-mentioned repo.

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    rebase-strategy: disabled
    schedule:
      interval: "cron"
      cronjob: "0 1 * * *"
      timezone: "America/New_York"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/"
    rebase-strategy: disabled
    schedule:
      interval: "cron"
      cronjob: "30 1 * * *"
      timezone: "America/New_York"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    rebase-strategy: disabled
    schedule:
      interval: "cron"
      cronjob: "0 2 * * *"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    groups:
      docker-actions:
        applies-to: version-updates
        patterns:
          - "docker/*"
      github-actions:
        applies-to: version-updates
        patterns:
          - "actions/*"
          - "github/*"
      lizardbyte-actions:
        applies-to: version-updates
        patterns:
          - "LizardByte/*"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    rebase-strategy: disabled
    schedule:
      interval: "cron"
      cronjob: "30 2 * * *"
      timezone: "America/New_York"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/"
    rebase-strategy: disabled
    schedule:
      interval: "cron"
      cronjob: "0 3 * * *"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        applies-to: version-updates
        dependency-type: "development"

  - package-ecosystem: "nuget"
    directory: "/"
    rebase-strategy: disabled
    schedule:
      interval: "cron"
      cronjob: "30 3 * * *"
      timezone: "America/New_York"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/"
    rebase-strategy: disabled
    schedule:
      interval: "cron"
      cronjob: "0 4 * * *"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    groups:
      pytest-dependencies:
        applies-to: version-updates
        patterns:
          - "pytest*"

  - package-ecosystem: "rust-toolchain"
    directory: "/"
    rebase-strategy: disabled
    schedule:
      interval: "cron"
      cronjob: "30 4 * * *"
      timezone: "America/New_York"
    open-pull-requests-limit: 1
