---
# This action is centrally managed in https://github.com/<organization>/.github/
# Don't make changes to this file in this repo as they will be overwritten with changes made to the same file in
# the above-mentioned repo.

blank_issues_enabled: false
contact_links:
  - name: Support Center
    url: https://app.lizardbyte.dev/support
    about: Official LizardByte support
  - name: Feature request
    url: https://app.lizardbyte.dev/feedback
    about: Share your suggestions or ideas to help us improve
