---
# https://openapi.tools

openapi: 3.1.0

info:
  title: Sunshine
  summary: Self-hosted game stream host for Moonlight.
  version: 0.0.0
  contact:
    name: LizardByte
    url: https://app.lizardbyte.dev/support
  license:
    name: GNU General Public License v3.0 only
    url: https://github.com/LizardByte/Sunshine/blob/master/LICENSE

servers:
  - url: "https://{host}:{ui-port}"
    description: Sunshine server
    variables:
      host:
        default: "localhost"
      ui-port:
        default: 47990

security:
  - basicAuth: []

components:
  securitySchemes:
    # TODO: update when JWT is implemented (https://github.com/LizardByte/Sunshine/pull/2995)
    # https://swagger.io/specification/#security-scheme-object-examples
    basicAuth:
      description: HTTP Basic authentication
      type: http
      scheme: basic

paths:
  /api/apps:
    $ref: "./paths/confighttp/apps/apps.yml"
  /api/apps/{index}:
    $ref: "./paths/confighttp/apps/apps-by-index.yml"
  /api/logs:
    $ref: "./paths/confighttp/logs/logs.yml"
