---
# This workflow is centrally managed in https://github.com/LizardByte/.github/
# Don't make changes to this file in this repo as they will be overwritten with changes made to the same file in
# the above-mentioned repo.

# To use, add the `pacman-pkg` repository label to identify repositories that should trigger this workflow.

# Update pacman repo on release events.

name: Update pacman repo
permissions:
  contents: read

on:
  release:
    types:
      - released

concurrency:
  group: "${{ github.workflow }}-${{ github.event.release.tag_name }}"
  cancel-in-progress: true

jobs:
  update-homebrew-release:
    name: Update pacman repo
    uses: LizardByte/.github/.github/workflows/__call-update-pacman-repo.yml@master
    if: github.repository_owner == 'LizardByte'
    secrets:
      GH_EMAIL: ${{ secrets.GH_BOT_EMAIL }}
      GH_NAME: ${{ secrets.GH_BOT_NAME }}
      GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
