# This action is centrally managed in https://github.com/<organization>/.github/
# Don't make changes to this file in this repo as they will be overwritten with changes made to the same file in
# the above-mentioned repo.

# This workflow is designed to work with:
# - automerge workflows

# It uses GitHub Action that auto-updates pull requests branches, when changes are pushed to their destination branch.
# Auto-updating to the latest destination branch works only in the context of upstream repo and not forks.

name: autoupdate

on:
  push:
    branches:
      - 'nightly'

jobs:
  autoupdate-for-bot:
    name: Autoupdate autoapproved PR created in the upstream
    if: startsWith(github.repository, 'LizardByte/')
    runs-on: ubuntu-latest
    steps:
      - name: Update
        uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ secrets.GH_BOT_TOKEN }}'
          PR_FILTER: "labelled"
          PR_LABELS: "autoupdate"
          PR_READY_STATE: "ready_for_review"
          MERGE_CONFLICT_ACTION: "ignore"
