name: clang-format-lint

on:
  pull_request:
    branches: [master, nightly]
    types: [opened, synchronize, edited, reopened]

jobs:
  lint:
    name: Clang Format Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Clang format lint
      uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: './sunshine'
        extensions: 'cpp,h,m,mm'
        clangFormatVersion: 13
        style: file
        inplace: false

    - name: Upload Artifacts
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: sunshine
        path: sunshine/
