name: Issues

on:
  issues:
    types: [labeled, unlabeled]

jobs:
  label:
    name: Label Issues
    runs-on: ubuntu-latest
    steps:
      - name: Label Issues
        uses: dessant/label-actions@v2
        with:
          github-token: ${{ github.token }}
