name: Label Actions

on:
  issues:
    types: [labeled, unlabeled]
  discussion:
    types: [ labeled, unlabeled ]

jobs:
  label:
    name: Label Actions
    runs-on: ubuntu-latest
    steps:
      - name: Label Actions
        uses: dessant/label-actions@v2
        with:
          github-token: ${{ github.token }}
