---
name: Release Notifications (Moonlight)
permissions: {}

on:
  release:
    types:
      - released  # this triggers when a release is published, but does not include prereleases or drafts

jobs:
  discord:
    if: github.repository_owner == 'LizardByte'
    runs-on: ubuntu-latest
    steps:
      - name: Check if latest GitHub release
        id: check-release
        uses: actions/github-script@v8
        with:
          script: |
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            core.setOutput('isLatestRelease', latestRelease.data.tag_name === context.payload.release.tag_name);

      - name: discord
        if: steps.check-release.outputs.isLatestRelease == 'true'
        uses: sarisia/actions-status-discord@v1
        with:
          avatar_url: ${{ vars.ORG_LOGO_URL }}256
          color: 0x${{ vars.COLOR_HEX_GREEN }}
          description: ${{ github.event.release.body }}
          nodetail: true
          nofail: false
          title: ${{ github.event.repository.name }} ${{ github.ref_name }} Released
          username: ${{ secrets.DISCORD_USERNAME }}
          webhook: ${{ secrets.DISCORD_RELEASE_WEBHOOK_MOONLIGHT }}
