---
name: Publish to WinGet

on:
  release:
    types: [released]

jobs:
  winget-releaser:
    name: winget releaser
    runs-on: windows-latest
    steps:
      - name: winget releaser
        uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: LizardByte.Sunshine
          token: ${{ secrets.GH_BOT_TOKEN }}
